name: Packer CI - Status Check

on:
  pull_request:
    paths:
      - '**/*.pkr.hcl'
      - '**/*.pkrvars.hcl'

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Packer Vars File from Secrets
        run: |
          cat <<EOF > custom.pkrvars.hcl
          aws_region       = "${{ secrets.AWS_REGION }}"
          source_ami       = "${{ secrets.SOURCE_AMI }}"
          instance_type    = "${{ secrets.INSTANCE_TYPE }}"
          ssh_username     = "${{ secrets.SSH_USERNAME }}"
          ami_name_prefix  = "${{ secrets.AMI_NAME_PREFIX }}"
          jar_source       = "${{ secrets.JAR_SOURCE }}"
          jar_destination  = "${{ secrets.JAR_DESTINATION }}"
          db_url           = "${{ secrets.DB_URL }}"
          db_username      = "${{ secrets.DB_USERNAME }}"
          db_password      = "${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
          unzip -o packer_1.8.0_linux_amd64.zip
          sudo mv packer /usr/local/bin/


      - name: Check Packer Formatting
        run: packer fmt -check .
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Validate Packer Template
        run: packer validate -var-file=custom.pkrvars.hcl amazon-custom-image.pkr.hcl
