name: Packer CI - Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Installing Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Check Packer Formatting
        run: |
          cd packer
          packer fmt -check .

      - name: Generate Packer Vars File from Secrets
        run: |
          cd packer
          echo 'aws_region       = "${{ secrets.AWS_REGION }}"' > custom.pkrvars.hcl
          echo 'source_ami       = "${{ secrets.SOURCE_AMI }}"' >> custom.pkrvars.hcl
          echo 'instance_type    = "${{ secrets.INSTANCE_TYPE }}"' >> custom.pkrvars.hcl
          echo 'ssh_username     = "${{ secrets.SSH_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'ami_name_prefix  = "${{ secrets.AMI_NAME_PREFIX }}"' >> custom.pkrvars.hcl
          echo 'jar_source       = "${{ secrets.JAR_SOURCE }}"' >> custom.pkrvars.hcl
          echo 'jar_destination  = "${{ secrets.JAR_DESTINATION }}"' >> custom.pkrvars.hcl
          echo 'db_url           = "${{ secrets.DB_URL }}"' >> custom.pkrvars.hcl
          echo 'db_username      = "${{ secrets.DB_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'db_password      = "${{ secrets.DB_PASSWORD }}"' >> custom.pkrvars.hcl
          echo 'gcp_project       = "${{ secrets.GCP_PROJECT }}"' >> custom.pkrvars.hcl
          echo 'gcp_zone          = "${{ secrets.GCP_ZONE }}"' >> custom.pkrvars.hcl
          echo 'gcp_instance_type = "${{ secrets.GCP_INSTANCE_TYPE }}"' >> custom.pkrvars.hcl
          echo 'gcp_ssh_username  = "${{ secrets.GCP_SSH_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'image_name_prefix  = "${{ secrets.GCP_IMAGE_PREFIX }}"' >> custom.pkrvars.hcl
          echo 'gcp_jar_source       = "${{ secrets.JAR_SOURCE }}"' >> custom.pkrvars.hcl
          echo 'gcp_jar_destination  = "${{ secrets.JAR_DESTINATION }}"' >> custom.pkrvars.hcl
          echo 'gcp_db_url           = "${{ secrets.DB_URL }}"' >> custom.pkrvars.hcl
          echo 'gcp_db_username      = "${{ secrets.DB_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'gcp_db_password      = "${{ secrets.DB_PASSWORD }}"' >> custom.pkrvars.hcl
      
## jar_source=target/webapp-0.0.1-SNAPSHOT.jar
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Packer Plugins
        run: |
          cd packer
          packer init .
          
      - name: Create dummy Jar file
        run: |
          mkdir -p target
          touch target/webapp-0.0.1-SNAPSHOT.jar


      - name: Validate AWS Packer Template
        run: packer validate -var-file=packer/custom.pkrvars.hcl packer/amazon-custom-packer.pkr.hcl

      - name: Validate GCP Packer Template
        run: packer validate -var-file=packer/custom.pkrvars.hcl packer/gcp-custom-packer.pkr.hcl

