name: Packer CI - Status Check

on:
  pull_request:
    paths:
      - '**/*.pkr.hcl'
      - '**/*.pkrvars.hcl'

jobs:
  packer-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Packer Vars File from Secrets
        run: |
          echo 'aws_region       = "${{ secrets.AWS_REGION }}"' > custom.pkrvars.hcl
          echo 'source_ami       = "${{ secrets.SOURCE_AMI }}"' >> custom.pkrvars.hcl
          echo 'instance_type    = "${{ secrets.INSTANCE_TYPE }}"' >> custom.pkrvars.hcl
          echo 'ssh_username     = "${{ secrets.SSH_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'ami_name_prefix  = "${{ secrets.AMI_NAME_PREFIX }}"' >> custom.pkrvars.hcl
          echo 'jar_source       = "${{ secrets.JAR_SOURCE }}"' >> custom.pkrvars.hcl
          echo 'jar_destination  = "${{ secrets.JAR_DESTINATION }}"' >> custom.pkrvars.hcl
          echo 'db_url           = "${{ secrets.DB_URL }}"' >> custom.pkrvars.hcl
          echo 'db_username      = "${{ secrets.DB_USERNAME }}"' >> custom.pkrvars.hcl
          echo 'db_password      = "${{ secrets.DB_PASSWORD }}"' >> custom.pkrvars.hcl


      - name: Installing Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"


      - name: Check Packer Formatting
        run: |
          cd packer
          packer fmt -check .

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Validate Packer Template
        run: packer validate -var-file=custom.pkrvars.hcl amazon-custom-image.pkr.hcl
