name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Jar Artifact
        uses: actions/download-artifact@v3
        with:
          name: springboot-app
          path: target

      - name: Change Directory to packer
        run: |
          cd packer

      - name: Generate Packer Vars File from Secrets
        run: |
          cat <<EOF > custom.pkrvars.hcl
          aws_region       = "${{ secrets.AWS_REGION }}"
          source_ami       = "${{ secrets.SOURCE_AMI }}"
          instance_type    = "${{ secrets.INSTANCE_TYPE }}"
          ssh_username     = "${{ secrets.SSH_USERNAME }}"
          ami_name_prefix  = "${{ secrets.AMI_NAME_PREFIX }}"
          jar_source       = "target/webapp-0.0.1-SNAPSHOT.jar"
          jar_destination  = "${{ secrets.JAR_DESTINATION }}"
          db_url           = "${{ secrets.DB_URL }}"
          db_username      = "${{ secrets.DB_USERNAME }}"
          db_password      = "${{ secrets.DB_PASSWORD }}"
          EOF

      - name: Installing Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init packer/amazon-custom-packer.pkr.hcl"
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Custom AMI with Packer
        run: packer build -var-file=packer/custom.pkrvars.hcl packer/amazon-custom-packer.pkr.hcl
