name: Spring Boot CI

on:
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: healthcheckdb
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      # Set your DB connection URL; adjust as needed by your app.
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      # jdbc:mysql://localhost:3306/healthcheckdb
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Maven Tests
        run: mvn test
      
      # - name: Build Jar Artifact
      #   run: mvn clean package -DskipTests

      # - name: Upload Jar Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: springboot-app
      #     path: target/*.jar
